In [1]:
import numpy as np

# Basic

In [2]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# For dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# For shape
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# For type
a.dtype

dtype('int32')

In [10]:
b.dtype

dtype('float64')

In [11]:
# For size
a.itemsize

4

In [12]:
b.itemsize

8

In [13]:
# For total size
a.nbytes

12

In [14]:
b.nbytes

48

In [15]:
# For number of elements
a.size

3

In [16]:
b.size

6

# Accessing and changing specific elements,rows,col,etc

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
#  For specific element [r,c]
a[1,5]

13

In [19]:
# For specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# For specific column
a[:, 2]

array([ 3, 10])

In [21]:
# For a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [22]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
# For specific element (work outside in)
b[0,1,1]

4

# Initializing Different Types of Arrays

In [28]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [30]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [31]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [32]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.28021363, 0.7735661 ],
       [0.16883978, 0.64304877],
       [0.40284748, 0.42626806],
       [0.87844576, 0.75459576]])

In [33]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-2,  2,  7],
       [-4, -1,  6],
       [ 5,  4, -2]])

In [34]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [36]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
# For copy array
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


# + - * / **

In [38]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [40]:
a + 2

array([3, 4, 5, 6])

In [41]:
a - 2

array([-1,  0,  1,  2])

In [42]:
a * 2

array([2, 4, 6, 8])

In [43]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [46]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [45]:
a ** 2

array([ 1,  4,  9, 16])

In [47]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# linear algebra

In [48]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [49]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# statistics

In [50]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
np.min(stats)

1

In [52]:
np.max(stats,axis=1)

array([3, 6])

In [53]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [54]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous
load data file

In [56]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean masking and advanced indexing

In [57]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])